### PR TITLE
Fixed cyrillic strings

### PR DESCRIPTION
**Pull request by goodmind**

### CODE REVIEW

**Comment by kondratyevdev** [comment]
return this.writeBytes(Buffer.from(str));  will fix for all strings

**Comment by goodmind** [comment]
@kondratyevdev didn't https://github.com/goodmind/telegram-tl-node/pull/3 fix this issue?

**Comment by kondratyevdev** [comment]
No... Today I can't send russian text when clone last version from this repository...

**Comment by goodmind** [comment]
Fixed by 66613a891f65dfe5af3214d5f9d0af8f63f22590

**Pull request closed without merging**
